# Site settings
title: g.raphaelli.com
email: g@raphaelli.com
description: Gil Raphaelli
baseurl: ""
url: "http://g.raphaelli.com"
github_username: graphaelli
linkedin_username: graphaelli
twitter_username: graphaelli

# github defaults
highlighter: rouge
safe: true
lsi: false

# Build settings
markdown: kramdown
