# Site settings
title:
email: g@raphaelli.com
description: Gilad Raphaelli
baseurl: ""
url: "http://g.raphaelli.com"
github_username: graphaelli
linkedin_username: graphaelli
twitter_username: graphaelli

# github defaults
highlighter: rouge
safe: true
lsi: false

# Build settings
markdown: kramdown
